### ISSUE TITLE
Requests from GM approval do Dispose Medjil IP

### ISSUE THREAD

**Issue by KentWheeler** [Landgate/Medjil#76]
- [x] Change the Medjil GitHub repository to public
- [ ] Deploy current version to UAT
    - [x] Timelines to deploy? (June/July)
    - [ ] Who is available to test application? (Kent /Khandu/Irek and Queensland. Issac)
    - [x] Who is doing application support? (Kent /Khandu)
    - [ ] Domain/URL (https://Medjil.es.landgate.wa.gov.au)
- [ ] Progress testing and production.
- [x] Apply Copyright and End User Terms and Conditions as advised in Memo
    - [x] Copyright Note added to each source file.
    - [x] #89
    - [x] Medjil Portal states "© 2023 Western Australian Land Information Authority"
    - [x] GitHub Page © 2022-2023 Western Australian Land Information Authority
- [ ] setup a Content Management folder. (Letitia)
- [x] Other recommendations from IP Memo
    - [x] End User Terms and Conditions (Memo 14.6)
    - [x] Accept all cookies
    - [x] remove the double page for Terms of use and privacy

**Comment by ibaran73** [comment]
GM has approved disposal of Medjil IP
